### ISSUE TITLE
Creating a new release overwrites binaries of a different release

### ISSUE THREAD

**Issue by fasmat** [spacemeshos/spacemesh-sdk#17]
I just created a release `v1.0.2-beta1` to test some changes that are not yet published and saw that the github action triggered from creating the release updated the binaries of Release `v1.0.1`.

It seems that pushing a commit on any branch will always create a new build and update the binaries of the latest release with it.

**Comment by fasmat** [comment]
Upon closer inspection this seems to be caused by the changes in https://github.com/spacemeshos/spacemesh-sdk/pull/5

since those are not merged yet I close the issue.

**Comment by lrettig** [comment]
thanks - yes - that's a temporary change and I'll revert it before merging
